<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
	</PropertyGroup>
	<Import Project="../TestProjects.props" />
	<PropertyGroup>
		<!-- as in MainSlnTest.props, for IsExternalInit etc. when targeting net8.0 -->
		<PolySharpExcludeTypeForwardedToDeclarations>true</PolySharpExcludeTypeForwardedToDeclarations>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="$(ProjectDir)../BizHawk.Emulation.Common/BizHawk.Emulation.Common.csproj" />
		<ProjectReference Include="$(ProjectDir)../BizHawk.Emulation.Cores/BizHawk.Emulation.Cores.csproj" />
	</ItemGroup>
</Project>
